-- Add shipping dimension columns to products table
ALTER TABLE products
ADD COLUMN IF NOT EXISTS weight NUMERIC(10,2) DEFAULT 0.5, -- in kg
ADD COLUMN IF NOT EXISTS length NUMERIC(10,2) DEFAULT 10,  -- in cm
ADD COLUMN IF NOT EXISTS breadth NUMERIC(10,2) DEFAULT 10, -- in cm
ADD COLUMN IF NOT EXISTS height NUMERIC(10,2) DEFAULT 10,  -- in cm
ADD COLUMN IF NOT EXISTS hsn VARCHAR(20);

-- Add Shiprocket specific columns to orders table
ALTER TABLE orders
ADD COLUMN IF NOT EXISTS shiprocket_order_id VARCHAR(50),
ADD COLUMN IF NOT EXISTS shipment_id VARCHAR(50),
ADD COLUMN IF NOT EXISTS awb_code VARCHAR(50),
ADD COLUMN IF NOT EXISTS courier_name VARCHAR(100),
ADD COLUMN IF NOT EXISTS tracking_url TEXT,
ADD COLUMN IF NOT EXISTS tracking_status VARCHAR(50),
ADD COLUMN IF NOT EXISTS pickup_location VARCHAR(100),
ADD COLUMN IF NOT EXISTS shipping_cost NUMERIC(10,2) DEFAULT 0,
ADD COLUMN IF NOT EXISTS estimated_delivery TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS manifest_url TEXT,
ADD COLUMN IF NOT EXISTS label_url TEXT,
ADD COLUMN IF NOT EXISTS invoice_url TEXT,
ADD COLUMN IF NOT EXISTS last_tracking_sync TIMESTAMP WITH TIME ZONE;
